/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.krtirtho

import org.gradle.api.tasks.bundling.Zip

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class SpotubeGradlePluginPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.plugins.withId("app.cash.zipline") {
            registerPackageTask(
                project,
                "development",
                "compileDevelopmentExecutableKotlinJsZipline"
            )
            registerPackageTask(project, "production", "compileProductionExecutableKotlinJsZipline")
        }
    }

    fun registerPackageTask(project: Project, flavor: String, compileTaskName: String) {
        val capitalizedFlavor = flavor.replaceFirstChar { it.uppercase() }

        project.tasks.register("package${capitalizedFlavor}Plugin", Zip::class.java) {
            group = "distribution"
            description =
                "Packages the $flavor Zipline executable and plugin.json into a smplug."

            // 1. Depend on the Zipline compilation task
            dependsOn(project.tasks.named(compileTaskName))

            // 2. Set the output location and name
            archiveFileName.set("plugin-$flavor.smplug")
            destinationDirectory.set(project.layout.buildDirectory.dir("distributions"))

            // 3. Include the Zipline outputs
            // We use a provider/closure to ensure the directory exists when the task runs
            from(project.layout.buildDirectory.dir("zipline/$capitalizedFlavor")) {
                // This preserves subdirectories if Zipline generated any
                include("**/*")
            }

            // 4. Include plugin.json
            // Use layout.projectDirectory.file() to reach the root JSON
            from(project.layout.projectDirectory.file("plugin.json"))

            // Set inputs for incremental build support
            inputs.file(project.layout.projectDirectory.file("plugin.json"))
        }
    }
}
